<?php

/**
 * @internal this code has been auto-generated by the phplrt compiler v4.1.1
 */

declare(strict_types=1);

namespace TypeLang\Parser\Internal;

use TypeLang\Parser\Exception;
use TypeLang\Type;

\interface_exists(\Phplrt\Contracts\Source\Exception\SourceExceptionInterface::class);
\interface_exists(\Phplrt\Contracts\Source\ReadableInterface::class);
\interface_exists(\Phplrt\Contracts\Source\FileInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\ChannelInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\TokenInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\LexerInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\Exception\LexerExceptionInterface::class);
\interface_exists(\Phplrt\Contracts\Lexer\Exception\RuntimeExceptionInterface::class);
\enum_exists(\Phplrt\Contracts\Lexer\Channel::class);
\class_exists(\Phplrt\Contracts\Lexer\UserDefinedChannel::class);
\interface_exists(\Phplrt\Contracts\Parser\ParserInterface::class);
\interface_exists(\Phplrt\Contracts\Parser\Exception\ParserExceptionInterface::class);
\interface_exists(\Phplrt\Contracts\Parser\Exception\RuntimeExceptionInterface::class);

/**
 * @template TResult of mixed = mixed
 *
 * @template-implements \Phplrt\Contracts\Parser\ParserInterface<TResult>
 */
abstract class CompiledExecutor implements \Phplrt\Contracts\Parser\ParserInterface
{
    /** @var int */
    public const T_WHITESPACE = 0;
    /** @var int */
    public const T_EQ = 1;
    /** @var int */
    public const T_NOT = 2;
    /** @var int */
    public const T_TRUE_LITERAL = 3;
    /** @var int */
    public const T_FALSE_LITERAL = 4;
    /** @var int */
    public const T_NULL_LITERAL = 5;
    /** @var int */
    public const T_NAME_WITH_SPACE = 6;
    /** @var int */
    public const T_NAME = 7;
    /** @var int */
    public const T_NS_DELIMITER = 8;
    /** @var int */
    public const T_OR = 9;
    /** @var int */
    public const T_COMMA = 10;
    /** @var int */
    public const T_DOUBLE_COLON = 11;
    /** @var int */
    public const T_COLON = 12;
    /** @var int */
    public const T_ANGLE_BRACKET_OPEN = 13;
    /** @var int */
    public const T_ANGLE_BRACKET_CLOSE = 14;
    /** @var int */
    public const T_QMARK = 15;
    /** @var int */
    public const T_BRACE_OPEN = 16;
    /** @var int */
    public const T_BRACE_CLOSE = 17;
    /** @var int */
    public const T_PARENTHESIS_OPEN = 18;
    /** @var int */
    public const T_PARENTHESIS_CLOSE = 19;
    /** @var int */
    public const T_SQUARE_BRACKET_OPEN = 20;
    /** @var int */
    public const T_SQUARE_BRACKET_CLOSE = 21;
    /** @var int */
    public const T_AMP = 22;
    /** @var int */
    public const T_ELLIPSIS = 23;
    /** @var int */
    public const T_ASSIGN = 24;
    /** @var int */
    public const T_ASTERISK = 25;
    /** @var int */
    public const T_THIS = 26;
    /** @var int */
    public const T_VARIABLE = 27;
    /** @var int */
    public const T_DQ_STRING_LITERAL = 28;
    /** @var int */
    public const T_SQ_STRING_LITERAL = 29;
    /** @var int */
    public const T_FLOAT_LITERAL = 30;
    /** @var int */
    public const T_BIN_INT_LITERAL = 31;
    /** @var int */
    public const T_OCT_INT_LITERAL = 32;
    /** @var int */
    public const T_HEX_INT_LITERAL = 33;
    /** @var int */
    public const T_DEC_INT_LITERAL = 34;
    /** @var int */
    public const T_COMMENT = 35;
    /** @var int */
    public const T_DOC_COMMENT = 36;

    /** @var array<int, non-empty-string> */
    private const PARSER_EXPECTATIONS = [
        'T_WHITESPACE',
        'T_EQ',
        'T_NOT',
        'T_TRUE_LITERAL',
        'T_FALSE_LITERAL',
        'T_NULL_LITERAL',
        'T_NAME_WITH_SPACE',
        'T_NAME',
        'T_NS_DELIMITER',
        'T_OR',
        'T_COMMA',
        'T_DOUBLE_COLON',
        'T_COLON',
        'T_ANGLE_BRACKET_OPEN',
        'T_ANGLE_BRACKET_CLOSE',
        'T_QMARK',
        'T_BRACE_OPEN',
        'T_BRACE_CLOSE',
        'T_PARENTHESIS_OPEN',
        'T_PARENTHESIS_CLOSE',
        'T_SQUARE_BRACKET_OPEN',
        'T_SQUARE_BRACKET_CLOSE',
        'T_AMP',
        'T_ELLIPSIS',
        'T_ASSIGN',
        'T_ASTERISK',
        'T_THIS',
        'T_VARIABLE',
        'T_DQ_STRING_LITERAL',
        'T_SQ_STRING_LITERAL',
        'T_FLOAT_LITERAL',
        'T_BIN_INT_LITERAL',
        'T_OCT_INT_LITERAL',
        'T_HEX_INT_LITERAL',
        'T_DEC_INT_LITERAL',
        'T_COMMENT',
        'T_DOC_COMMENT',
        '/[^\\s]++/',
    ];

    /** @var array<int, non-empty-string> */
    private const PARSER_MESSAGES = [
        5 => 'Syntax error, unexpected {token}, a nullable type must carry the type it makes nullable, for example "?T"',
        10 => 'Syntax error, unexpected {token}, a group must be closed with a bracket ")"',
        41 => 'Syntax error, unexpected {token}, a name must carry a segment after the separator, for example "Some\\Any"',
        46 => 'Syntax error, unexpected {token}, a class constant must carry a name after the double colon, for example "Some::CONST"',
        72 => 'Syntax error, unexpected {token}, a parameter list must be closed with a bracket ")"',
        76 => 'Syntax error, unexpected {token}, a callable must carry a type after the colon ":"',
        80 => 'Syntax error, unexpected {token}, an argument list must carry at least one argument',
        87 => 'Syntax error, unexpected {token}, an argument list must be closed with a bracket ">"',
        91 => 'Syntax error, unexpected {token}, a parameter list must carry at least one parameter',
        100 => 'Syntax error, unexpected {token}, a parameter list must be closed with a bracket ">"',
        115 => 'Syntax error, unexpected {token}, a shape field must carry a type after the colon ":"',
        124 => 'Syntax error, unexpected {token}, a shape must be closed with a brace "}"',
        131 => 'Syntax error, unexpected {token}, an offset must be closed with a bracket "]"',
        136 => 'Syntax error, unexpected {token}, a union type must carry a type after the vertical bar "|", for example "T|U"',
        138 => 'Syntax error, unexpected {token}, an intersection type must carry a type after the ampersand "&", for example "T&U"',
        144 => 'Syntax error, unexpected {token}, a condition must carry the type it is true of',
        'Syntax error, unexpected {token}, a condition must be parted with a colon ":"',
        'Syntax error, unexpected {token}, a condition must carry the type it is false of',
    ];

    /** @var array<int, bool> */
    private const PARSER_KEPT_TABLE = [
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        true,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
    ];

    /** @var array<int, array<int, true>|null> */
    private const PARSER_START_PREDICTION_TABLE = [
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            15 => true,
            18 => true,
            25 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            15 => true,
            18 => true,
            25 => true,
            true,
            28 => true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            15 => true,
            18 => true,
            25 => true,
            true,
            28 => true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            15 => true,
        ],
        [
            15 => true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            18 => true,
            25 => true,
            true,
            28 => true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            18 => true,
            25 => true,
            true,
            28 => true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            18 => true,
            25 => true,
            true,
            28 => true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            18 => true,
        ],
        [
            18 => true,
        ],
        [
            19 => true,
        ],
        [
            26 => true,
        ],
        [
            3 => true,
            true,
            true,
            28 => true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            3 => true,
            true,
            28 => true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            28 => true,
            true,
        ],
        [
            28 => true,
        ],
        [
            29 => true,
        ],
        [
            30 => true,
        ],
        [
            31 => true,
            true,
            true,
            true,
        ],
        [
            31 => true,
        ],
        [
            32 => true,
        ],
        [
            33 => true,
        ],
        [
            34 => true,
        ],
        [
            3 => true,
        ],
        [
            4 => true,
        ],
        [
            5 => true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        null,
        [
            8 => true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            7 => true,
        ],
        [
            6 => true,
        ],
        [
            1 => true,
        ],
        [
            2 => true,
        ],
        [
            3 => true,
        ],
        [
            4 => true,
        ],
        [
            5 => true,
        ],
        null,
        [
            8 => true,
        ],
        [
            8 => true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        null,
        [
            8 => true,
            11 => true,
            13 => true,
            16 => true,
            18 => true,
            25 => true,
        ],
        [
            11 => true,
        ],
        [
            11 => true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            25 => true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        null,
        [
            25 => true,
        ],
        [
            25 => true,
        ],
        null,
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        null,
        [
            18 => true,
        ],
        null,
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            15 => true,
            18 => true,
            25 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            15 => true,
            18 => true,
            25 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        null,
        [
            22 => true,
        ],
        null,
        [
            23 => true,
        ],
        null,
        [
            26 => true,
            true,
        ],
        [
            27 => true,
        ],
        [
            26 => true,
        ],
        null,
        [
            24 => true,
        ],
        null,
        [
            10 => true,
        ],
        [
            10 => true,
        ],
        null,
        [
            19 => true,
        ],
        null,
        [
            12 => true,
        ],
        [
            12 => true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            15 => true,
            18 => true,
            25 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            13 => true,
        ],
        [
            13 => true,
        ],
        [
            13 => true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            15 => true,
            18 => true,
            25 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            15 => true,
            18 => true,
            25 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            6 => true,
        ],
        [
            6 => true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            15 => true,
            18 => true,
            25 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        null,
        [
            10 => true,
        ],
        [
            14 => true,
        ],
        null,
        [
            13 => true,
        ],
        [
            13 => true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        null,
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            24 => true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            24 => true,
        ],
        [
            24 => true,
        ],
        null,
        [
            10 => true,
        ],
        [
            14 => true,
        ],
        [
            16 => true,
        ],
        [
            16 => true,
        ],
        null,
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            15 => true,
            18 => true,
            25 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            15 => true,
            18 => true,
            25 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            15 => true,
            18 => true,
            25 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            18 => true,
            25 => true,
            true,
            28 => true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            18 => true,
            25 => true,
            true,
            28 => true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        null,
        [
            12 => true,
            15 => true,
        ],
        null,
        null,
        [
            15 => true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            15 => true,
            18 => true,
            25 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            15 => true,
            18 => true,
            25 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        null,
        [
            10 => true,
        ],
        null,
        [
            10 => true,
        ],
        [
            23 => true,
        ],
        null,
        null,
        [
            17 => true,
        ],
        [
            8 => true,
        ],
        [
            25 => true,
        ],
        null,
        [
            20 => true,
        ],
        [
            20 => true,
        ],
        null,
        [
            21 => true,
        ],
        null,
        [
            9 => true,
            22 => true,
        ],
        [
            9 => true,
        ],
        [
            9 => true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            15 => true,
            18 => true,
            25 => true,
            true,
            28 => true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            22 => true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            15 => true,
            18 => true,
            25 => true,
            true,
            28 => true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        null,
        [
            1 => true,
        ],
        [
            1 => true,
        ],
        null,
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            15 => true,
            18 => true,
            25 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            15 => true,
            18 => true,
            25 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            12 => true,
        ],
        [
            1 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            15 => true,
            18 => true,
            25 => true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
        ],
        [
            26 => true,
            true,
        ],
    ];

    /** @var array<int, array<int, list<int>>> */
    private const PARSER_CHOICE_PREDICTION_TABLE = [
        [
            1 => [
                1,
            ],
            [
                1,
            ],
            [
                1,
            ],
            [
                1,
            ],
            [
                1,
            ],
            [
                1,
            ],
            [
                1,
            ],
            [
                1,
            ],
            15 => [
                1,
            ],
            18 => [
                1,
            ],
            25 => [
                1,
            ],
            28 => [
                1,
            ],
            [
                1,
            ],
            [
                1,
            ],
            [
                1,
            ],
            [
                1,
            ],
            [
                1,
            ],
            [
                1,
            ],
            27 => [
                147,
            ],
        ],
        2 => [
            15 => [
                3,
            ],
            1 => [
                6,
            ],
            2 => [
                6,
            ],
            3 => [
                6,
            ],
            4 => [
                6,
            ],
            5 => [
                6,
            ],
            6 => [
                6,
            ],
            7 => [
                6,
            ],
            8 => [
                6,
            ],
            18 => [
                6,
            ],
            25 => [
                6,
            ],
            [
                6,
            ],
            28 => [
                6,
            ],
            [
                6,
            ],
            [
                6,
            ],
            [
                6,
            ],
            [
                6,
            ],
            [
                6,
            ],
            [
                6,
            ],
        ],
        7 => [
            18 => [
                8,
            ],
            26 => [
                -12,
            ],
            3 => [
                12,
                26,
            ],
            4 => [
                12,
                26,
            ],
            5 => [
                12,
                26,
            ],
            28 => [
                12,
            ],
            [
                12,
            ],
            [
                12,
            ],
            [
                12,
            ],
            [
                12,
            ],
            [
                12,
            ],
            [
                12,
            ],
            1 => [
                26,
            ],
            2 => [
                26,
            ],
            6 => [
                26,
            ],
            7 => [
                26,
            ],
            8 => [
                26,
            ],
            25 => [
                126,
            ],
        ],
        12 => [
            3 => [
                13,
            ],
            [
                13,
            ],
            28 => [
                13,
            ],
            [
                13,
            ],
            [
                13,
            ],
            [
                13,
            ],
            [
                13,
            ],
            [
                13,
            ],
            [
                13,
            ],
            5 => [
                -26,
            ],
        ],
        [
            28 => [
                14,
            ],
            [
                14,
            ],
            [
                -18,
            ],
            [
                18,
            ],
            [
                18,
            ],
            [
                18,
            ],
            [
                18,
            ],
            3 => [
                -24,
            ],
            4 => [
                -25,
            ],
        ],
        [
            28 => [
                -16,
            ],
            [
                -17,
            ],
        ],
        18 => [
            31 => [
                -20,
            ],
            [
                -21,
            ],
            [
                -22,
            ],
            [
                -23,
            ],
        ],
        30 => [
            7 => [
                -32,
            ],
            6 => [
                -33,
            ],
            1 => [
                -34,
            ],
            2 => [
                -35,
            ],
            3 => [
                -36,
            ],
            4 => [
                -37,
            ],
            5 => [
                -38,
            ],
        ],
        43 => [
            11 => [
                44,
            ],
            18 => [
                54,
            ],
            13 => [
                77,
                89,
            ],
            16 => [
                101,
            ],
            25 => [
                49,
            ],
            8 => [
                125,
            ],
        ],
        46 => [
            1 => [
                47,
            ],
            [
                47,
            ],
            [
                47,
            ],
            [
                47,
            ],
            [
                47,
            ],
            [
                47,
            ],
            [
                47,
            ],
            25 => [
                49,
            ],
        ],
        63 => [
            27 => [
                -65,
            ],
            26 => [
                -66,
            ],
        ],
        81 => [
            1 => [
                84,
            ],
            [
                84,
            ],
            [
                84,
            ],
            [
                84,
            ],
            [
                84,
            ],
            7 => [
                84,
            ],
            [
                84,
            ],
            15 => [
                84,
            ],
            18 => [
                84,
            ],
            25 => [
                84,
            ],
            [
                84,
            ],
            [
                84,
            ],
            [
                84,
            ],
            [
                84,
            ],
            [
                84,
            ],
            [
                84,
            ],
            [
                84,
            ],
            [
                84,
            ],
            [
                84,
            ],
        ],
        84 => [
            25 => [
                -51,
                0,
            ],
            1 => [
                0,
            ],
            2 => [
                0,
            ],
            3 => [
                0,
            ],
            4 => [
                0,
            ],
            5 => [
                0,
            ],
            6 => [
                0,
            ],
            7 => [
                0,
            ],
            8 => [
                0,
            ],
            15 => [
                0,
            ],
            18 => [
                0,
            ],
            [
                0,
            ],
            [
                0,
            ],
            [
                0,
            ],
            [
                0,
            ],
            [
                0,
            ],
            [
                0,
            ],
            [
                0,
            ],
            [
                0,
            ],
            [
                0,
            ],
        ],
        94 => [
            1 => [
                95,
            ],
            [
                95,
            ],
            [
                95,
            ],
            [
                95,
            ],
            [
                95,
            ],
            [
                95,
            ],
            [
                95,
            ],
            24 => [
                96,
            ],
        ],
        106 => [
            15 => [
                116,
            ],
            27 => [
                116,
            ],
        ],
        108 => [
            8 => [
                7,
            ],
            18 => [
                7,
            ],
            25 => [
                7,
            ],
            [
                7,
            ],
            28 => [
                7,
            ],
            [
                7,
            ],
            [
                7,
            ],
            [
                7,
            ],
            [
                7,
            ],
            [
                7,
            ],
            [
                7,
            ],
        ],
        133 => [
            9 => [
                134,
            ],
            22 => [
                137,
            ],
        ],
        143 => [
            1 => [
                0,
            ],
            [
                0,
            ],
            [
                0,
            ],
            [
                0,
            ],
            [
                0,
            ],
            [
                0,
            ],
            [
                0,
            ],
            [
                0,
            ],
            15 => [
                0,
            ],
            18 => [
                0,
            ],
            25 => [
                0,
            ],
            28 => [
                0,
            ],
            [
                0,
            ],
            [
                0,
            ],
            [
                0,
            ],
            [
                0,
            ],
            [
                0,
            ],
            [
                0,
            ],
        ],
    ];

    /** @var array<int, list<int>> */
    private const PARSER_SEQUENCE_PREDICTION_TABLE = [
        1 => [
            2,
            132,
            -141,
        ],
        26 => [
            27,
            -44,
        ],
        [
            -30,
            30,
            38,
        ],
        47 => [
            30,
            -50,
        ],
        49 => [
            50,
            51,
            -31,
        ],
        54 => [
            9,
            55,
            72,
            -75,
        ],
        56 => [
            57,
            68,
            -71,
        ],
        [
            0,
            -60,
            -62,
            -64,
            -68,
        ],
        78 => [
            79,
            80,
            85,
            -71,
            87,
        ],
        90 => [
            79,
            91,
            98,
            -71,
            100,
        ],
        101 => [
            102,
            103,
            -71,
            124,
        ],
        104 => [
            105,
            -121,
        ],
        107 => [
            108,
            -115,
            75,
            115,
        ],
        111 => [
            -5,
            75,
        ],
        121 => [
            61,
            -79,
        ],
        126 => [
            50,
            30,
            -50,
        ],
        128 => [
            129,
            -1,
            131,
        ],
        141 => [
            33,
            -35,
        ],
    ];

    /**
     * @var \Phplrt\Parser\Parser<TResult>
     */
    protected readonly \Phplrt\Parser\Parser $parser;

    protected readonly \Phplrt\Contracts\Lexer\LexerInterface $lexer;

    public function __construct()
    {
        $this->lexer = new \Phplrt\Lexer\Lexer(
            pattern: '/\\G(?|(?:(?:\\s++)(*MARK:0))|(?:(?:is(?:(?!(?:[a-zA-Z0-9\\-_\\x80-\\xff]))))(*MARK:1))|(?:(?:not(?:(?!(?:[a-zA-Z0-9\\-_\\x80-\\xff]))))(*MARK:2))|(?:(?:(?i:true)(?:(?!(?:[a-zA-Z0-9\\-_\\x80-\\xff]))))(*MARK:3))|(?:(?:(?i:false)(?:(?!(?:[a-zA-Z0-9\\-_\\x80-\\xff]))))(*MARK:4))|(?:(?:(?i:null)(?:(?!(?:[a-zA-Z0-9\\-_\\x80-\\xff]))))(*MARK:5))|(?:(?:(?:[a-zA-Z_\\x80-\\xff])(?:[a-zA-Z0-9\\-_\\x80-\\xff])*+\\s++)(*MARK:6))|(?:(?:(?:[a-zA-Z_\\x80-\\xff])(?:[a-zA-Z0-9\\-_\\x80-\\xff])*+)(*MARK:7))|(?:(?:\\\\)(*MARK:8))|(?:(?:\\|)(*MARK:9))|(?:(?:,)(*MARK:10))|(?:(?:::)(*MARK:11))|(?:(?::)(*MARK:12))|(?:(?:<)(*MARK:13))|(?:(?:>)(*MARK:14))|(?:(?:\\?)(*MARK:15))|(?:(?:\\{)(*MARK:16))|(?:(?:\\})(*MARK:17))|(?:(?:\\()(*MARK:18))|(?:(?:\\))(*MARK:19))|(?:(?:\\[)(*MARK:20))|(?:(?:\\])(*MARK:21))|(?:(?:&)(*MARK:22))|(?:(?:\\.\\.\\.)(*MARK:23))|(?:(?:=)(*MARK:24))|(?:(?:\\*)(*MARK:25))|(?:(?:\\$this(?!(?:[a-zA-Z0-9_\\x80-\\xff])))(*MARK:26))|(?:(?:\\$(?:[a-zA-Z_\\x80-\\xff])(?:[a-zA-Z0-9_\\x80-\\xff])*+)(*MARK:27))|(?:(?:"[^"\\\\]*+(?:\\\\.[^"\\\\]*+)*+")(*MARK:28))|(?:(?:\'[^\'\\\\]*+(?:\\\\.[^\'\\\\]*+)*+\')(*MARK:29))|(?:(?:(?:[-+])?(?:(?:(?:(?:[0-9])(?:_?(?:[0-9]))*+)\\.(?:(?:(?:[0-9])(?:_?(?:[0-9]))*+))?|\\.(?:(?:[0-9])(?:_?(?:[0-9]))*+))(?:(?:[eE](?:[-+])?(?:(?:[0-9])(?:_?(?:[0-9]))*+)))?|(?:(?:[0-9])(?:_?(?:[0-9]))*+)(?:[eE](?:[-+])?(?:(?:[0-9])(?:_?(?:[0-9]))*+))))(*MARK:30))|(?:(?:(?:[-+])?0[bB](?:(?:[01])(?:_?(?:[01]))*+))(*MARK:31))|(?:(?:(?:[-+])?0(?:[oO](?:(?:[0-7])(?:_?(?:[0-7]))*+)|(?:_?(?:[0-7]))++))(*MARK:32))|(?:(?:(?:[-+])?0[xX](?:(?:[0-9a-fA-F])(?:_?(?:[0-9a-fA-F]))*+))(*MARK:33))|(?:(?:(?:[-+])?(?:(?:(?:[1-9])(?:_?(?:[0-9]))*+)|0))(*MARK:34))|(?:(?:(?:\\/\\/|\\#)[^\\r\\n]*+)(*MARK:35))|(?:(?:\\/\\*.*?\\*\\/)(*MARK:36))|(?:(?:[^\\s]++)(*MARK:37)))/Ssm',
            channels: [
                'Hidden',
                35 => 'Hidden',
                'Hidden',
                'Unknown',
            ],
            names: [
                'T_WHITESPACE',
                'T_EQ',
                'T_NOT',
                'T_TRUE_LITERAL',
                'T_FALSE_LITERAL',
                'T_NULL_LITERAL',
                'T_NAME_WITH_SPACE',
                'T_NAME',
                'T_NS_DELIMITER',
                'T_OR',
                'T_COMMA',
                'T_DOUBLE_COLON',
                'T_COLON',
                'T_ANGLE_BRACKET_OPEN',
                'T_ANGLE_BRACKET_CLOSE',
                'T_QMARK',
                'T_BRACE_OPEN',
                'T_BRACE_CLOSE',
                'T_PARENTHESIS_OPEN',
                'T_PARENTHESIS_CLOSE',
                'T_SQUARE_BRACKET_OPEN',
                'T_SQUARE_BRACKET_CLOSE',
                'T_AMP',
                'T_ELLIPSIS',
                'T_ASSIGN',
                'T_ASTERISK',
                'T_THIS',
                'T_VARIABLE',
                'T_DQ_STRING_LITERAL',
                'T_SQ_STRING_LITERAL',
                'T_FLOAT_LITERAL',
                'T_BIN_INT_LITERAL',
                'T_OCT_INT_LITERAL',
                'T_HEX_INT_LITERAL',
                'T_DEC_INT_LITERAL',
                'T_COMMENT',
                'T_DOC_COMMENT',
            ],
        );

        $this->parser = new \Phplrt\Parser\Parser(
            lexer: $this->lexer,
            grammar: [
                new \Phplrt\Parser\Grammar\Alternation([1, 147]),
                new \Phplrt\Parser\Grammar\Concatenation([2, 132, 139]),
                new \Phplrt\Parser\Grammar\Alternation([3, 6]),
                new \Phplrt\Parser\Grammar\Concatenation([4, 5]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_QMARK, false),
                new \Phplrt\Parser\Grammar\Concatenation([6]),
                new \Phplrt\Parser\Grammar\Concatenation([7, 127]),
                new \Phplrt\Parser\Grammar\Alternation([8, 11, 12, 26, 126]),
                new \Phplrt\Parser\Grammar\Concatenation([9, 0, 10]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PARENTHESIS_OPEN, false),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PARENTHESIS_CLOSE, false),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_THIS, true),
                new \Phplrt\Parser\Grammar\Alternation([13, 25]),
                new \Phplrt\Parser\Grammar\Alternation([14, 17, 18, 23, 24]),
                new \Phplrt\Parser\Grammar\Alternation([15, 16]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_DQ_STRING_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SQ_STRING_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_FLOAT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Alternation([19, 20, 21, 22]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BIN_INT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_OCT_INT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_HEX_INT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_DEC_INT_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_TRUE_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_FALSE_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NULL_LITERAL, true),
                new \Phplrt\Parser\Grammar\Concatenation([27, 42]),
                new \Phplrt\Parser\Grammar\Concatenation([28, 30, 38]),
                new \Phplrt\Parser\Grammar\Optional(29),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NS_DELIMITER, true),
                new \Phplrt\Parser\Grammar\Alternation([31, 32, 33, 34, 35, 36, 37]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NAME, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NAME_WITH_SPACE, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_EQ, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NOT, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_TRUE_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_FALSE_LITERAL, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NULL_LITERAL, true),
                new \Phplrt\Parser\Grammar\Repetition(39, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([40, 41]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NS_DELIMITER, false),
                new \Phplrt\Parser\Grammar\Concatenation([30]),
                new \Phplrt\Parser\Grammar\Optional(43),
                new \Phplrt\Parser\Grammar\Alternation([44, 54, 77, 89, 101, 49, 125]),
                new \Phplrt\Parser\Grammar\Concatenation([45, 46]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_DOUBLE_COLON, true),
                new \Phplrt\Parser\Grammar\Alternation([47, 49]),
                new \Phplrt\Parser\Grammar\Concatenation([30, 48]),
                new \Phplrt\Parser\Grammar\Optional(49),
                new \Phplrt\Parser\Grammar\Concatenation([50, 51, 53]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ASTERISK, true),
                new \Phplrt\Parser\Grammar\Repetition(52, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([30, 50]),
                new \Phplrt\Parser\Grammar\Optional(30),
                new \Phplrt\Parser\Grammar\Concatenation([9, 55, 72, 73]),
                new \Phplrt\Parser\Grammar\Optional(56),
                new \Phplrt\Parser\Grammar\Concatenation([57, 68, 71]),
                new \Phplrt\Parser\Grammar\Concatenation([0, 58, 60, 62, 66]),
                new \Phplrt\Parser\Grammar\Optional(59),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_AMP, true),
                new \Phplrt\Parser\Grammar\Optional(61),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ELLIPSIS, true),
                new \Phplrt\Parser\Grammar\Optional(63),
                new \Phplrt\Parser\Grammar\Alternation([64, 65]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_VARIABLE, true),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_THIS, true),
                new \Phplrt\Parser\Grammar\Optional(67),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ASSIGN, true),
                new \Phplrt\Parser\Grammar\Repetition(69, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([70, 57]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_COMMA, false),
                new \Phplrt\Parser\Grammar\Optional(70),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_PARENTHESIS_CLOSE, false),
                new \Phplrt\Parser\Grammar\Optional(74),
                new \Phplrt\Parser\Grammar\Concatenation([75, 76]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_COLON, false),
                new \Phplrt\Parser\Grammar\Concatenation([0]),
                new \Phplrt\Parser\Grammar\Concatenation([78, 88]),
                new \Phplrt\Parser\Grammar\Concatenation([79, 80, 85, 71, 87]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ANGLE_BRACKET_OPEN, false),
                new \Phplrt\Parser\Grammar\Concatenation([81]),
                new \Phplrt\Parser\Grammar\Alternation([82, 84]),
                new \Phplrt\Parser\Grammar\Concatenation([83, 84]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_NAME_WITH_SPACE, true),
                new \Phplrt\Parser\Grammar\Alternation([50, 0]),
                new \Phplrt\Parser\Grammar\Repetition(86, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([70, 81]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ANGLE_BRACKET_CLOSE, false),
                new \Phplrt\Parser\Grammar\Predicate(9, false),
                new \Phplrt\Parser\Grammar\Concatenation([90, 54]),
                new \Phplrt\Parser\Grammar\Concatenation([79, 91, 98, 71, 100]),
                new \Phplrt\Parser\Grammar\Concatenation([92]),
                new \Phplrt\Parser\Grammar\Concatenation([30, 93]),
                new \Phplrt\Parser\Grammar\Repetition(94, 0, \INF),
                new \Phplrt\Parser\Grammar\Alternation([95, 96]),
                new \Phplrt\Parser\Grammar\Concatenation([30, 0]),
                new \Phplrt\Parser\Grammar\Concatenation([97, 0]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ASSIGN, false),
                new \Phplrt\Parser\Grammar\Repetition(99, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([70, 92]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_ANGLE_BRACKET_CLOSE, false),
                new \Phplrt\Parser\Grammar\Concatenation([102, 103, 71, 124]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BRACE_OPEN, false),
                new \Phplrt\Parser\Grammar\Alternation([104, 123]),
                new \Phplrt\Parser\Grammar\Concatenation([105, 119]),
                new \Phplrt\Parser\Grammar\Concatenation([106, 117]),
                new \Phplrt\Parser\Grammar\Alternation([107, 116]),
                new \Phplrt\Parser\Grammar\Concatenation([108, 113, 75, 115]),
                new \Phplrt\Parser\Grammar\Alternation([109, 7]),
                new \Phplrt\Parser\Grammar\Concatenation([30, 110]),
                new \Phplrt\Parser\Grammar\Predicate(111, true),
                new \Phplrt\Parser\Grammar\Concatenation([112, 75]),
                new \Phplrt\Parser\Grammar\Optional(4),
                new \Phplrt\Parser\Grammar\Optional(114),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_QMARK, true),
                new \Phplrt\Parser\Grammar\Concatenation([0]),
                new \Phplrt\Parser\Grammar\Concatenation([0]),
                new \Phplrt\Parser\Grammar\Repetition(118, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([70, 106]),
                new \Phplrt\Parser\Grammar\Optional(120),
                new \Phplrt\Parser\Grammar\Concatenation([70, 121]),
                new \Phplrt\Parser\Grammar\Concatenation([61, 122]),
                new \Phplrt\Parser\Grammar\Optional(78),
                new \Phplrt\Parser\Grammar\Optional(121),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_BRACE_CLOSE, false),
                new \Phplrt\Parser\Grammar\Concatenation([40, 49]),
                new \Phplrt\Parser\Grammar\Concatenation([50, 30, 48]),
                new \Phplrt\Parser\Grammar\Repetition(128, 0, \INF),
                new \Phplrt\Parser\Grammar\Concatenation([129, 130, 131]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SQUARE_BRACKET_OPEN, false),
                new \Phplrt\Parser\Grammar\Optional(0),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_SQUARE_BRACKET_CLOSE, false),
                new \Phplrt\Parser\Grammar\Repetition(133, 0, \INF),
                new \Phplrt\Parser\Grammar\Alternation([134, 137]),
                new \Phplrt\Parser\Grammar\Concatenation([135, 136]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_OR, true),
                new \Phplrt\Parser\Grammar\Concatenation([2]),
                new \Phplrt\Parser\Grammar\Concatenation([59, 138]),
                new \Phplrt\Parser\Grammar\Concatenation([2]),
                new \Phplrt\Parser\Grammar\Optional(140),
                new \Phplrt\Parser\Grammar\Concatenation([141, 143, 4, 144, 145, 146]),
                new \Phplrt\Parser\Grammar\Concatenation([33, 142]),
                new \Phplrt\Parser\Grammar\Optional(34),
                new \Phplrt\Parser\Grammar\Alternation([0, 63]),
                new \Phplrt\Parser\Grammar\Concatenation([0]),
                new \Phplrt\Parser\Grammar\Lexeme(self::T_COLON, false),
                new \Phplrt\Parser\Grammar\Concatenation([0]),
                new \Phplrt\Parser\Grammar\Concatenation([63, 140]),
            ],
            initial: 0,
            reducers: [
                0 => $this->reduceType(...),
                3 => self::reduceNullableType(...),
                6 => $this->reduceListOrOffsetType(...),
                11 => self::reduceThisType(...),
                12 => $this->reduceLiteralType(...),
                15 => self::reduceDoubleQuotedStringLiteralType(...),
                16 => self::reduceSingleQuotedStringLiteralType(...),
                17 => self::reduceFloatLiteralType(...),
                18 => self::reduceIntLiteralType(...),
                23 => self::reduceTrueLiteralType(...),
                24 => self::reduceFalseLiteralType(...),
                25 => self::reduceNullLiteralType(...),
                26 => $this->reduceNamedType(...),
                27 => self::reduceName(...),
                30 => self::reduceIdentifier(...),
                50 => self::reduceWildcardType(...),
                55 => self::reduceCallableParameters(...),
                57 => self::reduceCallableParameter(...),
                63 => self::reduceVariable(...),
                78 => $this->reduceTemplateArguments(...),
                81 => $this->reduceTemplateArgument(...),
                83 => self::reduceIdentifierWithExtraSpace(...),
                90 => $this->reduceTemplateParameters(...),
                92 => self::reduceTemplateParameter(...),
                95 => self::reduceTemplateBoundEdge(...),
                101 => $this->reduceShapeFields(...),
                105 => self::reduceShapeFieldsList(...),
                107 => self::reduceExplicitField(...),
                116 => self::reduceImplicitField(...),
                125 => self::reduceNamespacedMask(...),
                126 => self::reduceLeadingMaskType(...),
                128 => self::reduceListOrOffsetSuffix(...),
                141 => self::reduceTernaryExpressionOperator(...),
            ],
            expectations: self::PARSER_EXPECTATIONS,
            messages: self::PARSER_MESSAGES,
            kept: self::PARSER_KEPT_TABLE,
            startPrediction: self::PARSER_START_PREDICTION_TABLE,
            choicePrediction: self::PARSER_CHOICE_PREDICTION_TABLE,
            sequencePrediction: self::PARSER_SEQUENCE_PREDICTION_TABLE,
        );
    }

    public function parse(\Phplrt\Contracts\Source\ReadableInterface $source): mixed
    {
        return $this->parser->parse($source);
    }

    private function reduceType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        if (\count($children) === 1) {
            return $children[0];
        }

        // The suffix of a condition is the only thing the rule reads that carries
        // a flag of its own, which is what the operands are told from
        $condition = null;

        for ($i = 1, $count = \count($children); $i < $count; ++$i) {
            if (\is_bool($children[$i])) {
                $condition = \array_splice($children, $i);

                break;
            }
        }

        // The operands joined by an ampersand bind tighter, so they are collected
        // into a group of their own, and the groups are what a union is made of
        $groups = [];
        $group = [$children[0]];
        $isUnion = false;
        $isIntersection = false;

        for ($i = 1, $count = \count($children); $i < $count; $i += 2) {
            if ($children[$i]->id === self::T_OR) {
                $isUnion = true;
                $groups[] = $group;
                $group = [$children[$i + 1]];

                continue;
            }

            $isIntersection = true;
            $group[] = $children[$i + 1];
        }

        $groups[] = $group;

        // The operand that binds tighter is the one reported first, the way the
        // reading would have reached it
        if ($isIntersection && $this->features->intersections === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('intersection types', $source, $offset);
        }

        if ($isUnion && $this->features->unions === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('union types', $source, $offset);
        }

        $statements = [];

        foreach ($groups as $group) {
            $statements[] = \count($group) === 1
                ? $group[0]
                : new Type\IntersectionTypeNode($group, $group[0]->offset);
        }

        $statement = \count($statements) === 1
            ? $statements[0]
            : new Type\UnionTypeNode($statements, $offset);

        if ($condition === null) {
            return $statement;
        }

        if ($this->features->conditions === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('conditional expressions', $source, $offset);
        }

        $comparison = $condition[0]
            ? new Type\Condition\NotEqualConditionNode($statement, $condition[1], $offset)
            : new Type\Condition\EqualConditionNode($statement, $condition[1], $offset);

        return new Type\TernaryExpressionNode(
            $comparison,
            $condition[2],
            $condition[3],
            $offset,
        );
    }

    private static function reduceNullableType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\NullableTypeNode($children[0], $offset);
    }

    private function reduceListOrOffsetType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        $statement = $children[0];
        $count = \count($children);

        for ($i = 1; $i < $count; ++$i) {
            $child = $children[$i];

            switch (true) {
                case $child === true:
                    if ($this->features->lists === false) {
                        throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('square bracket list types', $source, $offset);
                    }

                    $statement = new Type\TypesListNode($statement, $offset);
                    break;
                case $child instanceof Type\TypeNode:
                    if ($this->features->offsets === false) {
                        throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('type offsets', $source, $offset);
                    }

                    $statement = new Type\TypeOffsetAccessNode($statement, $child, $offset);
                    break;
                default:
                    throw Exception\InternalSemanticException::becauseSubNodeIsUnexpected(
                        \get_debug_type($child),
                        $source,
                        $offset,
                    );
            }
        }

        return $statement;
    }

    private static function reduceThisType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\ThisNode($offset);
    }

    private function reduceLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        if ($this->features->literals === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('literal values', $source, $offset);
        }

        return $children;
    }

    private static function reduceDoubleQuotedStringLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\StringLiteralNode(
            StringDecoder::unpackAndDecode($children->value, true),
            $children->value,
            $offset,
        );
    }

    private static function reduceSingleQuotedStringLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\StringLiteralNode(
            StringDecoder::unpackAndDecode($children->value, false),
            $children->value,
            $offset,
        );
    }

    private static function reduceFloatLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\FloatLiteralNode(
            FloatDecoder::decode($children->value),
            $children->value,
            $offset,
        );
    }

    private static function reduceIntLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        $decoded = IntDecoder::decode($children->value);

        return new Type\Literal\IntLiteralNode(
            $decoded->value,
            $children->value,
            $decoded->decimal,
            $offset,
        );
    }

    private static function reduceTrueLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\BoolLiteralNode(true, $children->value, $offset);
    }

    private static function reduceFalseLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\BoolLiteralNode(false, $children->value, $offset);
    }

    private static function reduceNullLiteralType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Literal\NullLiteralNode(
            $children->value,
            $offset,
        );
    }

    private function reduceNamedType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        $head = $children[0];
        $suffix = $children[1] ?? null;

        // "Some\Any\*" and "Some\Any\SOME_*"
        //
        // A mask closes the type it is written at the end of, so it is read as a
        // suffix of a name and never carries a suffix of its own.
        if ($suffix instanceof Type\MaskNode || $suffix instanceof Type\WildcardNode) {
            $parts = $head->parts;

            if ($suffix instanceof Type\MaskNode) {
                // "Some\Any\*"
                $mask = $suffix;
            } else {
                // "Some\Any\SOME_*"
                $segment = \array_pop($parts);
                $mask = new Type\MaskNode([$segment, ...\array_slice($children, 1)], $segment->offset);
            }

            return new Type\ConstMaskNode(
                $mask,
                $parts === []
                    ? $head->isFullyQualified
                    : new Type\Name($parts, $head->isFullyQualified, $head->offset),
                $offset,
            );
        }

        switch (true) {
            // Some\Any
            case $suffix === null:
                return new Type\NamedTypeNode($children[0], null, null, $offset);

                // Some\Any<T, U>
            case $suffix instanceof Type\Template\TemplateArgumentListNode:
                return new Type\NamedTypeNode($children[0], $suffix, null, $offset);

                // Some\Any{name: T, ...<K, V>}
            case $suffix instanceof Type\Shape\FieldsListNode:
                return new Type\NamedTypeNode($children[0], $children[2] ?? null, $suffix, $offset);

                // Some\Any(T, U): V
            case $suffix instanceof Type\Callable\CallableParameterListNode:
                if ($this->features->callables === false) {
                    throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('callable types', $source, $offset);
                }

                return new Type\CallableTypeNode($children[0], $suffix, $children[2] ?? null, null, $offset);

                // Some\Any<T, U>(T): U
            case $suffix instanceof Type\Template\TemplateParameterListNode:
                if ($this->features->callables === false) {
                    throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('callable types', $source, $offset);
                }

                return new Type\CallableTypeNode($children[0], $children[2], $children[3] ?? null, $suffix, $offset);

                // Some\Any::CONST, Some\Any::CONST_* and Some\Any::*
            default:
                if (\count($children) === 3 && $children[2] instanceof Type\Identifier) {
                    return new Type\ClassConstNode($children[0], $children[2], $offset);
                }

                return new Type\ClassConstMaskNode(
                    $children[0],
                    new Type\MaskNode(\array_slice($children, 2), $children[2]->offset),
                    $offset,
                );
        }
    }

    private static function reduceName(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        // "Some\Any" starts at a segment of its own
        if ($children[0] instanceof Type\Identifier) {
            return new Type\Name($children, false, $offset);
        }

        // "\Some\Any" carries the separator in front of its segments, and the
        // name itself is the part that follows it
        $segments = \array_slice($children, 1);

        return new Type\Name($segments, true, $segments[0]->offset);
    }

    private static function reduceIdentifier(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Identifier(
            $children->id === self::T_NAME_WITH_SPACE
                ? \rtrim($children->value)
                : $children->value,
            $offset,
        );
    }

    private static function reduceWildcardType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\WildcardNode($offset);
    }

    private static function reduceCallableParameters(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Callable\CallableParameterListNode($children, $offset);
    }

    private static function reduceCallableParameter(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        $parameter = new Type\Callable\CallableParameterNode(
            $children[0],
            null,
            false,
            false,
            false,
            $offset,
        );

        for ($i = 1, $count = \count($children); $i < $count; ++$i) {
            $child = $children[$i];

            if ($child instanceof Type\VariableNode) {
                $parameter->name = $child;

                continue;
            }

            switch ($child->id) {
                case self::T_AMP:
                    $parameter->isOutput = true;
                    break;

                case self::T_ELLIPSIS:
                    $parameter->isVariadic = true;
                    break;

                default:
                    if ($parameter->isVariadic) {
                        throw Exception\VariadicWithDefaultException::becauseVariadicHasDefault($source, $offset);
                    }

                    $parameter->isOptional = true;
            }
        }

        return $parameter;
    }

    private static function reduceVariable(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\VariableNode(
            new Type\Identifier(\substr($children->value, 1), $offset),
            $offset,
        );
    }

    private function reduceTemplateArguments(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        if ($this->features->generics === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('template arguments', $source, $offset);
        }

        return new Type\Template\TemplateArgumentListNode($children, $offset);
    }

    private function reduceTemplateArgument(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        if (\is_array($children)) {
            if ($this->features->hints === false) {
                throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('template argument hints', $source, $offset);
            }

            return new Type\Template\TemplateArgumentNode($children[1], $children[0], $offset);
        }

        return new Type\Template\TemplateArgumentNode($children, null, $offset);
    }

    private static function reduceIdentifierWithExtraSpace(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Identifier(\rtrim($children->value), $offset);
    }

    private function reduceTemplateParameters(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        if ($this->features->generics === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('template parameters', $source, $offset);
        }

        return new Type\Template\TemplateParameterListNode($children, $offset);
    }

    private static function reduceTemplateParameter(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        $upper = $lower = $default = null;

        foreach (\array_slice($children, 1) as $limit) {
            if (!$limit instanceof Type\Template\TemplateBoundEdgeNode) {
                if ($default !== null) {
                    throw Exception\TemplateBoundException::becauseBoundIsDuplicated('default', $source, $limit->offset);
                }

                $default = $limit;

                continue;
            }

            if ($default !== null) {
                throw Exception\TemplateBoundException::becauseDefaultIsNotWrittenLast($source, $limit->operator->offset);
            }

            switch ($limit->operator->value) {
                case 'of':
                case 'as':
                    if ($upper !== null) {
                        throw Exception\TemplateBoundException::becauseBoundIsDuplicated('upper bound', $source, $limit->offset);
                    }

                    $upper = $limit;
                    break;

                case 'super':
                    if ($lower !== null) {
                        throw Exception\TemplateBoundException::becauseBoundIsDuplicated('lower bound', $source, $limit->offset);
                    }

                    $lower = $limit;
                    break;

                default:
                    throw Exception\TemplateBoundException::becauseOperatorIsUnknown(
                        $limit->operator->value,
                        $source,
                        $limit->operator->offset,
                    );
            }
        }

        return new Type\Template\TemplateParameterNode($children[0], $upper, $lower, $default, $offset);
    }

    private static function reduceTemplateBoundEdge(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Template\TemplateBoundEdgeNode($children[0], $children[1], $offset);
    }

    private function reduceShapeFields(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        $count = \count($children);

        if ($count === 0) {
            return [new Type\Shape\FieldsListNode([], true, $offset)];
        }

        if ($this->features->shapes === false) {
            throw Exception\FeatureNotAllowedException::becauseFeatureIsNotAllowed('shape fields', $source, $offset);
        }

        $parameters = null;

        // The "...<K, V>" suffix
        if ($children[$count - 1] instanceof Type\Template\TemplateArgumentListNode) {
            $parameters = $children[$count - 1];
            --$count;
        }

        if ($children[0] instanceof Type\Shape\FieldsListNode) {
            $fields = $children[0];
            $unsealed = $count > 1;
        } else {
            $fields = new Type\Shape\FieldsListNode([], true, $offset);
            $unsealed = $count > 0;
        }

        if ($unsealed) {
            $fields->isSealed = false;
        }

        if ($parameters === null) {
            return [$fields];
        }

        return [$fields, $parameters];
    }

    private static function reduceShapeFieldsList(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        $explicit = false;
        $implicit = false;
        $indexed = [];

        foreach ($children as $field) {
            if (!$field instanceof Type\Shape\ExplicitFieldNode) {
                $implicit = true;

                continue;
            }

            $explicit = true;

            if (!$field instanceof Type\Shape\SimpleFieldNodeInterface) {
                continue;
            }

            $key = $field->getIndex();

            if (isset($indexed[$key])) {
                throw Exception\ShapeFieldDuplicationException::becauseShapeFieldIsDuplicated($key, $source, $field->offset);
            }

            $indexed[$key] = true;
        }

        if ($explicit && $implicit) {
            throw Exception\ShapeKeysMixingException::becauseShapeKeysAreMixed($source, $offset);
        }

        return new Type\Shape\FieldsListNode($children, true, $offset);
    }

    private static function reduceExplicitField(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $source = $ctx->source;
        $offset = $ctx->begin;

        $count = \count($children);
        $name = $children[0];
        $value = $children[$count - 1];

        $optional = $count === 3;

        return match (true) {
            // "a", "true" and "null"
            $name instanceof Type\Identifier
                => new Type\Shape\NamedFieldNode($name, $value, $optional, $offset),
            $name instanceof Type\Literal\IntLiteralNode,
            $name instanceof Type\Literal\StringLiteralNode
                => new Type\Shape\ScalarFieldNode($name, $value, $optional, $offset),
            // "Some::CONST", "Some::CONST_*" and "JSON_*"
            $name instanceof Type\ClassConstNode,
            $name instanceof Type\ClassConstMaskNode,
            $name instanceof Type\ConstMaskNode
                => new Type\Shape\ComplexFieldNode($name, $value, $optional, $offset),
            default => throw Exception\ShapeKeyException::becauseKeyIsNotAName($source, $name->offset),
        };
    }

    private static function reduceImplicitField(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\Shape\ImplicitFieldNode($children[0], false, $offset);
    }

    private static function reduceNamespacedMask(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\MaskNode($children, $offset);
    }

    private static function reduceLeadingMaskType(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        // The variables below are declared by the compiler
        $offset = $ctx->begin;

        return new Type\ConstMaskNode(new Type\MaskNode($children, $offset), false, $offset);
    }

    private static function reduceListOrOffsetSuffix(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return $children[0] ?? true;
    }

    private static function reduceTernaryExpressionOperator(\Phplrt\Parser\Context $ctx, mixed $children): mixed
    {
        return \count($children) === 2;
    }
}
